# Generated by Django 6.0.4 on 2026-04-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_organization_contributor_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_contributor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_organization',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_recipient',
            field=models.BooleanField(default=False),
        ),
    ]
