# Generated by Django 6.0.4 on 2026-05-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
